### ISSUE TITLE
Wrong Cocoapods installation Pendo SDK 3.X  on Xcode 15.2  

### ISSUE THREAD

**Issue by ht-dmytro-yushko** [pendo-io/pendo-mobile-sdk#113]
**Platform + Version**
 iOS 15+, CocoaPods 1.15.1, Xcode 15.2, 

**SDK Version**
 Pendo SDK 3.X 

**Framework**
 Native, SwiftUI included

**Describe the bug**
After success `pod install` Pendo SDK was not available for import on the App level.

**To Reproduce**
1. Download example project
2. Run `bundle install`
3. Run `bundle exec pod install`
4. Try to build project 

**Expected behavior**
The project builds and runs without any issues

**Sample Code**
[ExamplePendo.zip](https://github.com/pendo-io/pendo-mobile-sdk/files/14224083/ExamplePendo.zip)

**Additional context**
We use CocoaPods as a dependency manager in our development and CI\CD. With Pendo we started work from SwiftUI beta SDK version `2.22.X` and are now considering migrating to the main SDK `3.X` version. Please suggest a solution for resolving this issue without changing the dependency manager.

**Comment by MikePendo** [comment]
Hi @ht-dmytro-yushko ,
Unfortunately the order of the **rpath**  does matter and should be aligned to default Xcode configs could you please change you **rpath** in the target to the following: `@executable_path/Frameworks, @loader_path/Frameworks`

**Comment by MikePendo** [comment]
I noticed that I also need to set NO  the `User Script Sandboxing`. 
https://developer.apple.com/forums/thread/731041?answerId=755722022#755722022 
(must admit not 100% sure how that related
See if that resolve your issue, If not we will need to dig a little bit more in to it )

**Comment by ht-dmytro-yushko** [comment]
@MikePendo I didn't have a enough time for check this today. I will back with feedback tomorrow.

**Comment by ht-dmytro-yushko** [comment]
Hi @MikePendo 

I finished playing with different settings with the XCode project. And it didn't help.

However, the updating of Cocoapods to the next version `1.15.2` on the local and CI/CD machines resolved this issue.  
Thanks for your assistance
