### ISSUE TITLE
Track event are not logging in IOS (Flutter)

### ISSUE THREAD

**Issue by ebabhi** [pendo-io/pendo-mobile-sdk#116]
**Platform + Version**
```
Flutter 3.16.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7f20e5d18c (3 months ago) • 2023-11-27 09:47:30 -0800
Engine • revision 22b600f240
Tools • Dart 3.2.1 • DevTools 2.28.3
```

**SDK Version**
pendo_sdk 3.1.0 

**Framework**
 Flutter

**Describe the bug**
When I call PendoSDK.track(event, parameters), I do not see the track event being logged in the Pendo dashboard under 'Raw Events', but the pre-defined events such as AppSessionStart, AppInForeground, and UpdateUserAttributes do get logged.

**To Reproduce**
Install the pendo_sdk 3.1.0  and try to log events on IOS platform using flutter

**Expected behavior**
when i log the track event  i should be able to see it in pendo dashboard (Raw Events)

**Logs**
There in  no error logs 
`flutter: [Pendo] [14:31:19.567] ✅ Channel: <track> was called with arguments: {EventName: HomePage, EventProperties: {screen: DashboardPage, home_item_clicked: My Parcels}}`

**Comment by 0xkuj** [comment]
Hi,
The track event you are sending looks valid.
You cannot, however, look for the event name you specified "HomePage" in your example, inside the raw events.
The event inside the raw events will be called "track", and inside it will contain the properties and name you sent about that specific event.
I am attaching an example we reproduced that has the same parameters as you mentioned in your log:
the track in the raw event list:
![Screenshot 2024-02-26 at 13 46 44](https://github.com/pendo-io/pendo-mobile-sdk/assets/56236821/383a9a2a-22a4-4040-b0c8-9f4cbd2f3d16)

the track description:
![image](https://github.com/pendo-io/pendo-mobile-sdk/assets/56236821/31c470ef-6e65-41dd-9e71-3717f5fae822)

also, you can look for that event inside pendo dashboard -> Product -> Track Events (they are not immediately updated like raw events, so take that into account)

Let me know if something is not working for you

**Comment by ebabhi** [comment]
![Screenshot 2024-02-27 at 9 01 22 am](https://github.com/pendo-io/pendo-mobile-sdk/assets/128349890/bdc48ec3-a797-42ca-b289-d46a1ec07838)

I am unable to track custom events. Only predefined events are logged automatically. However, my agent version is 3.1.0.8165, which is the latest version available on pub.dev, while yours is 3.1.0.1.

**Comment by ebabhi** [comment]
and i believe i have setup pendo sdk correctly 

![Screenshot 2024-02-27 at 9 46 05 am](https://github.com/pendo-io/pendo-mobile-sdk/assets/128349890/ce1eeb19-ae1c-40aa-9797-f0a80b78d63c)

**Comment by ebabhi** [comment]
In IOS, Track  event  get's only logged when i close the app or put the app in background, but in case of android  it gets logged instantly

**Comment by MikePendo** [comment]
In iOS we have a buffer of couple of events. on closing opening the app we send all the buffer.
The track event might be in that buffer, I think the size is 3-2 just send couple of track events snap you will see them

**Comment by MikePendo** [comment]
@ebabhi 
can you see if that make sense on your side

**Comment by ebabhi** [comment]
@MikePendo  i have tried with 10+ events they  gets only  logged  when i close or put app in background

**Comment by MikePendo** [comment]
mmm strange :( should work. any chance you can add us (ios-sdk@pendo.io) to your test flight so we can look in to it on our side. with explanation on which button you have the track event. or if you have the app on the appstore also fine (BUT in that case the SDK should be integrated). - assuming we can login to you app

**Comment by ebabhi** [comment]
we  haven't release the app yet , but i have notice one thing  if i send the event  through native app (app that host flutter engine )  the event gets logged instantly, here's the code 

```
       override func application(
           _ application: UIApplication,
           didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
       ) -> Bool {
           // configure firebase
           FirebaseApp.configure()
           
            AppDelegate.registerPlugins(with: self)
            UNUserNotificationCenter.current().delegate = self
           
            PendoManager.shared().setup("API_KEY")
            var visitorId = "John Doe"
            var accountId = "ACME"
            var visitorData: [String : any Hashable] = ["age": 27, "country": "USA"]
            var accountData: [String : any Hashable] = ["Tier": 1, "size": "Enterprise"]
            PendoManager.shared().startSession(visitorId, accountId:accountId, visitorData:visitorData, accountData:accountData)
            let eventProperties = ["propety1": "value1", "propety2": "value2"]
            PendoManager.shared().track("customEvent1", eventProperties)  


           // This is required to make any communication available in the action isolate.
           FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
               AppDelegate.registerPlugins(with: registry)
           }

           return super.application(application, didFinishLaunchingWithOptions: launchOptions)
       }
```

i think there is issue with flutter plugin itself

**Comment by MikePendo** [comment]
ok, lets do the following in your flutter app can you allow Pendo Logs `setDebugMode` before you call the setup.
Please run the app from within the Xcode and get us the native logs.
We should see the track event get logged if everything is correct. (In general the Flutter codless solution is straight forward and passes the track to the native if error occurs it should throw it)

**Comment by MikePendo** [comment]
@ebabhi 
Or if possible lets have a call with one of the TS

**Comment by ebabhi** [comment]
i have  opened a ticket in pendo support i hope i get response soon there :)

**Comment by MikePendo** [comment]
@ebabhi 
its just we need something to work with. either its logs or app or have a call with TS so we can see the issue. otherwise its hard to say why you dont see the track events displayed

**Comment by shlomipendo** [comment]
@ebabhi Hey, I'm closing this one as we'll continue the investigation via the support ticket with Pendo TS.
