### ISSUE TITLE
App is not receiving in app messages, log says  "screenContainer tag not found."

### ISSUE THREAD

**Issue by skadambala** [pendo-io/pendo-mobile-sdk#124]
**Platform + Version**
iOS 17.0

**Framework**
 React Native using React Navigation

**Describe the bug**
 App is not receiving in app messages. I created a guide to send a message to few selected pages in the app. But while navigating to these pages on app, I do not see the message.

 **_Looking at logs gives me this warning_** 
[rn-pendo-sdk]  analyze (simple flow) screenId:Options. Original error: findScreenContainerRootTag - screenContainer tag not found. 

Expected behaviour: 
App should receive in app messages as configured in guides.

**Comment by MikePendo** [comment]
Sounds like integration issue. 
Can you please share the snippet of your integration. 
From your description: you r trying to show guide on specific page?

**Comment by skadambala** [comment]
But I see these logs in when running via Xcode. ✅ Pendo Mobile SDK was successfully integrated and connected to the server. You can start adding guides to your app in our web console.

yes, I am trying to show guide on specific page of my app. 

Here is my integration snippet. 

in App.tsx,

import { NavigationContainer } from '@react-navigation/native';
import  { NavigationLibraryType, PendoSDK, WithPendoReactNavigation } from 'rn-pendo-sdk'    

function initPendo() {
  const navigationOptions = { library: NavigationLibraryType.ReactNavigation };
  const pendoKey = PENDO_KEY;
  PendoSDK.setup(pendoKey, navigationOptions);
}
initPendo();

const App: React.FC = (): React.JSX.Element => {
const PendoNavigationContainer = WithPendoReactNavigation(NavigationContainer);
return (
    <PermissionsProvider>
      <MenuProvider>
        <SafeAreaProvider>
          <GestureHandlerRootView style={{ flex: 1 }}>
            <MyAppProvider client={myAppClient}>
              <ApolloProvider client={apolloClient}>
                <DateProvider>
                  <LocaleProvider>
                    <MessageManagerProvider>
                      <PendoNavigationContainer
                        ref={navigationRef}
                        onReady={() => RNBootSplash.hide()}
                        fallback={<Text>{'Loading...'}</Text>}>
                        <CThemeProvider>
                          <AppStateProvider>
                            <AuthProvider>
                              <Navigation />
                            </AuthProvider>
                          </AppStateProvider>
                        </CThemeProvider>
                      </PendoNavigationContainer>
                    </MessageManagerProvider>
                  </LocaleProvider>
                </DateProvider>
              </ApolloProvider>
            </MyAppProvider>
          </GestureHandlerRootView>
        </SafeAreaProvider>
      </MenuProvider>
    </PermissionsProvider>
  );

}

**Comment by skadambala** [comment]
But I see these logs in when running via Xcode. ✅ Pendo Mobile SDK was successfully integrated and connected to the server. You can start adding guides to your app in our web console.

yes, I am trying to show guide on specific page of my app. I also see another log like this 

[rn-pendo-sdk]  State must not be null. 
 any analytics on this screen would be ignored 
 please refer to new installation instruction

Here is my integration snippet. 

in App.tsx,

import { NavigationContainer } from '@react-navigation/native';
import  { NavigationLibraryType, PendoSDK, WithPendoReactNavigation } from 'rn-pendo-sdk'    

function initPendo() {
  const navigationOptions = { library: NavigationLibraryType.ReactNavigation };
  const pendoKey = PENDO_KEY;
  PendoSDK.setup(pendoKey, navigationOptions);
}
initPendo();

const App: React.FC = (): React.JSX.Element => {
const PendoNavigationContainer = WithPendoReactNavigation(NavigationContainer);
return (
    <PermissionsProvider>
      <MenuProvider>
        <SafeAreaProvider>
          <GestureHandlerRootView style={{ flex: 1 }}>
            <MyAppProvider client={myAppClient}>
              <ApolloProvider client={apolloClient}>
                <DateProvider>
                  <LocaleProvider>
                    <MessageManagerProvider>
                      <PendoNavigationContainer
                        ref={navigationRef}
                        onReady={() => RNBootSplash.hide()}
                        fallback={<Text>{'Loading...'}</Text>}>
                        <CThemeProvider>
                          <AppStateProvider>
                            <AuthProvider>
                              <Navigation />
                            </AuthProvider>
                          </AppStateProvider>
                        </CThemeProvider>
                      </PendoNavigationContainer>
                    </MessageManagerProvider>
                  </LocaleProvider>
                </DateProvider>
              </ApolloProvider>
            </MyAppProvider>
          </GestureHandlerRootView>
        </SafeAreaProvider>
      </MenuProvider>
    </PermissionsProvider>
  );

}

**Comment by MikePendo** [comment]
Can you put 

_ const PendoNavigationContainer = WithPendoReactNavigation(NavigationContainer);_
Outside of the App function, just call it after the initPendo method

**Comment by MikePendo** [comment]
@skadambala 
Any progress on that?

**Comment by skadambala** [comment]
Adding the line outside app function did not help me. I still see screenContainer tag not found error.

**Comment by MikePendo** [comment]
@skadambala 
Can u share minimal sample project that represents the issue and we will debug it on our side

**Comment by skadambala** [comment]
After lot of attempts, upgrading react-navigation module from 6.1.7 to 6.1.17, my app started showing guides. You may close the issue.
