### ISSUE TITLE
Support for an alternate Pendo URL

### ISSUE THREAD

**Issue by jlawton** [pendo-io/pendo-mobile-sdk#126]
I make an app in which I'd like to use Pendo, but I have a requirement that all network requests from the app go to a very small set of well-known domains.

I would like to be able to forward traffic to Pendo servers through a domain I control, but I don't believe that the SDK has a capability to do that. Ideally, I could provide a URL, or set of URLs, and they would be the only network endpoints that the Pendo SDK would use.

**Comment by MikePendo** [comment]
You configure CNAMES

https://support.pendo.io/hc/en-us/articles/360047607631-Configure-CNAME-for-Pendo-Mobile
