### ISSUE TITLE
Android fails to compile

### ISSUE THREAD

**Issue by kg-currenxie** [pendo-io/pendo-mobile-sdk#143]
**Platform + Version**
Android + RN 0.70.13

```
        supportLibVersion = "33.0.0"
        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = '1.9.0'
```
and `distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip`

**SDK Version**
"rn-pendo-sdk": "3.2.0",

**Framework**
 React Native using React Navigation,

**Describe the bug**
Seems this package requires kotlin 1.9. So we upgraded that from 1.6.x. It built successfully. Then after adding the "rn-pendo-sdk", and the maven url, the app doesn't compile anymore.

**To Reproduce**
1. Have an app that compiles ✅
2. Add `rn-pendo-sdk` package ✅
3. Compile app with Pendo ❌ 
4. Remove the package, and recompile ✅

**Expected behavior**
Compilation to work

**Logs**
```

* What went wrong:
Execution failed for task ':app:checkStagingDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.play.core.common.IntentSenderForResultStarter found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.common.LocalTestingException found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.common.PlayCoreDialogWrapperActivity found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.listener.StateUpdatedListener found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.review.ReviewInfo found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-review-2.0.1-runtime (com.google.android.play:review:2.0.1)
     Duplicate class com.google.android.play.core.review.ReviewManager found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-review-2.0.1-runtime (com.google.android.play:review:2.0.1)
     Duplicate class com.google.android.play.core.review.ReviewManagerFactory found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-review-2.0.1-runtime (com.google.android.play:review:2.0.1)
     Duplicate class com.google.android.play.core.review.testing.FakeReviewManager found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-review-2.0.1-runtime (com.google.android.play:review:2.0.1)
```

**Comment by randmaayan** [comment]
Hi - 
please add the following to your _app/build.gradle_ - 
```
configurations.all {
       exclude group: 'com.google.android.play', module: 'review'
    }
```

please update us. thank you!

**Comment by df-currenxie** [comment]
> Hi - please add the following to your _app/build.gradle_ -
> 
> ```
> configurations.all {
>        exclude group: 'com.google.android.play', module: 'review'
>     }
> ```
> 
> please update us. thank you!

That worked, thanks @randmaayan. Maybe it could be included in the docs as well :)

**Comment by randmaayan** [comment]
We wanted to add a note here. 
If you're using _react-native-in-app-review_, upgrading to version 4.3.1 and later will resolve the duplicate class issue. 
You will not need to exclude any package.

**Comment by kg-currenxie** [comment]
> We wanted to add a note here. 
> 
> If you're using _react-native-in-app-review_, upgrading to version 4.3.1 and later will resolve the duplicate class issue. 
> 
> You will not need to exclude any package. 

Correct. We later found out this as well ✌️😊
