### ISSUE TITLE
Unable to start Pendo on release build

### ISSUE THREAD

**Issue by thechaudharysab** [pendo-io/pendo-mobile-sdk#161]
**Platform + Version**
"react-native": "0.73.6",
node v18.20.4

**SDK Version**
"rn-pendo-sdk": "3.3.0",

**Framework**
 React Native using React Navigation

**Describe the bug**

I'm unable launch pendo on iOS and Android Production/Release build.

I have different keys for staging and production in `.env` file of my project.  I added Pendo API key in it as well. I have been testing it on debug mode in the app and it seems to work fine. The moment I comment the staging keys and uncomment the release keys in my `.env` file (while the Pendo API key is the same) and creates a build it doesn't work when I try to Connect a Device using the QR or even if I open the URL and launch the app. It launches the app but the Pendo button doesn't appear.

I'm not sure what I am doing wrong in this case or if there is something that I am missing here. If it works in debug for my app it should work in production it's not like the bundle ID is different.

**To Reproduce**
1. Go to android build variants in android studio
2. Change it to release
3. Launch the app
4. Goto connect a device on pendo and try to open the app in release

**Comment by udilevin** [comment]
Are you also changing your app scheme as well? Different keys also means different scheme. Make sure that you update the scheme in your Android manifest and info.plist when changing keys
