### ISSUE TITLE
sendClickAnalytics method does not exist 

### ISSUE THREAD

**Issue by Joels-code** [pendo-io/pendo-mobile-sdk#169]
**Platform + Version**
iOS and Android

**SDK Version**
3.3.2

**Framework**
 React Native using React Navigation

**Describe the bug**
The API's documentation mentions a sendClickAnalytics method. However, trying to call this method results in an error. I can see in the node_modules rn-pendo-sdk pkg that it is not an exported method in the index.d.ts file.

**To Reproduce**
1. import PendoSDK from package
2. Attempt to call sendClickAnalytics

**Expected behavior**
The method is available for use as described in the API documentation.

**Sample Code**
![Screenshot 2024-08-28 at 11 04 51 AM](https://github.com/user-attachments/assets/8c8065f9-fb55-44f9-bbdd-c09156bb7b5f)

**Comment by MikePendo** [comment]
yes we forgot to export it unfortunately we will fix in next release

**Comment by randmaayan** [comment]
hi @Joels-code - 
we did forget to add it to the declaration file, so it's it not found by auto-complete.

please try typing it out and running the app.
to clarify, the API's name is **sendClickAnalytic** and not **sendClickAnalytics**

As Michael said, we will also add it to the declaration file in our next release for easier use.

**Comment by randmaayan** [comment]
@Joels-code done. thanks!
