### ISSUE TITLE
Pendo MAUI Nuget - Causes Android Build Errors

### ISSUE THREAD

**Issue by wynston-champion-actabl** [pendo-io/pendo-mobile-sdk#179]
Whenever the latest version of `pendo-maui` version - 3.3.2.8694 is installed, I am not able to build locally to Android. 

I get the following errors:

![image](https://github.com/user-attachments/assets/26416bca-a5c6-4369-9d51-4c63c6aac130)

![image](https://github.com/user-attachments/assets/0cd6f709-7d97-4ae6-99fa-f3f1c5ee1771)

I noticed that the following were also installed when the pendo-maui nuget was installed. Shouldn't `AndroidX` be used instead of `Android` when using MAUI? It seems like these packages are what is causing the build issue.

![image](https://github.com/user-attachments/assets/f906c980-4362-421f-be23-55cb584c9e61)

**Comment by noambartouv** [comment]
Hi @wynston-champion-actabl,

Our SDK contains these dependencies, allowing the prompt of an Android Play Review, available via our Pendo guides feature. There are no AndroidX equivalents for these libraries so I don't see this as an issue—[see nugget store](https://www.nuget.org/packages?q=play+review&includeComputedFrameworks=true&prerel=true&sortby=relevance). 

Are you perhaps importing Google Play reviews for usage in your application as well? This could explain why it's being generated more than once and then we could fix it by excluding one of the gradle imports.

**Comment by DavidPendo** [comment]
Hi @wynston-champion-actabl! Regarding your issue, can you please send us the list of your project dependency packages by running the ```dotnet list package --include-transitive```?

The **pendo-maui** nuget package contains only the 
```
Xamarin.Google.Android.Play.Core.Common                    2.0.3.2        
Xamarin.Google.Android.Play.Review                                2.0.1.3        
Xamarin.Google.Android.Play.Review.Ktx                          2.0.1.2       
```

So, if your project uses some other dependency, maybe ```PlayCore``` besides Pendo, it might cause the issue...  of more than one managed type... 

To exclude certain package from the project dependencies you can try to use 
```
<PackageReference Include="<<package-name>>" Version="<<version>>">
      <ExcludeAssets>All</ExcludeAssets>
</PackageReference>
```

! Remember that if you exclude the Pendo **Play** packages, the Pendo **in-app-rating** feature will not work.

**Comment by l0gaw** [comment]
Is there a workaround for that?

**Comment by DavidPendo** [comment]
Hi @l0gaw, the workaround is to exclude one of the conflicting packages, as was mentioned in the previous comment. In case the excluded package is of Pendo please note that it will affect the in-app-rating feature to not work.

**Comment by l0gaw** [comment]
Thanks. This workaround worked!

**Comment by wynston-champion-actabl** [comment]
@DavidPendo I am still having the same errors with the solution your provided above.

These are the packages I am using in my project:

   <PackageReference Include="Xamarin.AndroidX.Core" Version="1.13.1.2" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />

    <PackageReference Include="Xamarin.AndroidX.Collection" Version="1.4.0.5" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />

    <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.4.0.4" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />

    <PackageReference Include="Xamarin.AndroidX.Activity" Version="1.9.0.3" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />

    <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.9.0.3" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />

    <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.8.0.3" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />`
