### ISSUE TITLE
Technical support not provided for free account, but then cannot request via support to turn off IP location tracking

### ISSUE THREAD

**Issue by edorphy** [pendo-io/pendo-mobile-sdk#181]
**Platform + Version**
iOS 18

**SDK Version**
3.4.0

**Framework**
SwiftUI

**Describe the bug**
The Subscription Settings do not allow enabling or disabling of IP Location tracking, a support request is required. However, on a free account, users cannot create a support ticket. I followed the instructions [here](https://support.pendo.io/hc/en-us/articles/360034163971-Get-help-with-Pendo-from-Technical-Support) however the Support Center doesn't show me 'technical support' nor 'submit a ticket'.

So iOS apps that use the free subscription tier are forced into IP Location collection and therefore required to disclose it to users that our application is collecting location information per Apples requirements for [App Privacy Labels](https://developer.apple.com/app-store/app-privacy-details/).

Is this really expected? It seems that this will limit my ability to use Pendo because I do not want to be forced into putting in my privacy policy for low volume user apps that I collect location, nor have it listed as a badge of shame on the App Store page.

**To Reproduce**
1. Create a free account
2. Navigate to subscription settings
3. Read up on the feature, decide it needs to be turned off
4. No option to do so because free accounts do not support support tickets and the setting is not controllable via the subscription holder

>IP address and geolocation collectionOn by default, this setting allows Pendo to collect IP addresses and geolocation of your visitors. This data isn't displayed in the UI except the Exclude list. To update this setting, contact Pendo Support. | Enabled

IP address and geolocation collection
On by default, this setting allows Pendo to collect IP addresses and geolocation of your visitors. This data isn't displayed in the UI except the Exclude list. To update this setting, contact [Pendo Support](https://support.pendo.io/hc/en-us/articles/360034163971-Get-help-with-Pendo-from-Technical-Support).
Enabled

**Expected behavior**
Free accounts, irrespective of the reason should be able to disable IP Location Tracking. Developers shouldn't have to change their privacy model for any of these 'new subscription' use cases.
- Evaluating Pendo for new apps
- Apps below the MAU limits
- No paid subscription features needed

**Logs**
N/A

**Sample Code**
N/A

**Additional context**
N/A

**Comment by MikePendo** [comment]
@edorphy 
can you provide your subID?

**Comment by MikePendo** [comment]
@edorphy 
can you please provide your subID?

**Comment by edorphy** [comment]
@MikePendo where can the subID be found? I don't see anything in Settings > Organization Settings or Settings > Subscription Settings.

I appreciate you trying to fix this for me, but changing the settings one subscription at a time can't be sustainable. Thoughts on making it a feature that developers can control this themselves and not have to go through a support ticket?

https://developer.apple.com/app-store/review/guidelines/#privacy
https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy

**Comment by MikePendo** [comment]
in the url 
https://app.pendo.io/s/SUB_ID/home
@naorlevi FYI

**Comment by edorphy** [comment]
@MikePendo 6211122852855808

**Comment by MikePendo** [comment]
Done
