### ISSUE TITLE
[FLUTTER] - Exception when adding PendoNavigationObserver to MaterialApp navigatorObservers

### ISSUE THREAD

**Issue by arthurgiani** [pendo-io/pendo-mobile-sdk#183]
**Platform + Version**
iPhone 15 Pro Max, iOS 17.4

**SDK Version**
3.4.0
**Framework**
 Flutter

**Describe the bug**
When adding PendoNavigationObserver to MaterialApp navigatorObservers, the following error is thrown.

`FormatException: Positive input exceeds the limit of integer 61223625266189458655`

**To Reproduce**
1. Add Pendo SDK on Flutter
2. Init Pendo through PendoSDK.setup
3. Add PendoNavigationObserver to to MaterialApp navigatorObservers
4. See error message

**Expected behavior**
Add PendoSDK normally without errors.

**Logs**
No Pendo logs for this errors, this is a pure dart error.

StackTrace indicates that the error is happening on widget_info.dart file
![image](https://github.com/user-attachments/assets/d7b68f5f-be2a-45d4-a4b4-c445bdb2e679)
![image](https://github.com/user-attachments/assets/50800761-366f-4f82-bd99-9f6fb88cf77f)

**Sample Code**
Not Needed

**Comment by MikePendo** [comment]
@arthurgiani 
Will be fix in 3.4.1 early next week
