### ISSUE TITLE
Publish release notes for 3.4.1

### ISSUE THREAD

**Issue by edorphy** [pendo-io/pendo-mobile-sdk#185]
**Platform + Version**
iOS 18

**SDK Version**
3.4.1

**Framework**
Native

**Describe the bug**
The release notes have not been published for 3.4.1 yet but it looks like the git tag was created yesterday. 

**To Reproduce**
Go here and check for release notes for version 3.4.1: https://developers.pendo.io/category/mobile-sdk/

**Expected behavior**
Release notes are published. Ideally they are published with the git tag in GitHub under the releases feature, but if only published on the pendo.io website they should be available when new tags are available. Within a day should be reasonable.

**Logs**
n/a

**Sample Code**
n/a

**Additional context**
It might be coincidence, but with iOS 18 having just come out last week I suspect the changes are related to compatibility so I'm curious what has changed. Developers are hyper aware and pay close attention to dependency updates right after a major OS release.

**Comment by shlomipendo** [comment]
✅ https://developers.pendo.io/ios-native-sdk-3-4-1/

**Comment by edorphy** [comment]
Should the release notes state added support for NavigationSplitView? It says SwiftUI but references a UIKit framework type.

**Comment by MikePendo** [comment]
@edorphy 
you are right (its just under the hood in swiftUI its still UISplitViewController), I will try to change
