### ISSUE TITLE
💥 Crash on Pendo.startSession() `NullPointerException: getScreenManager(...) must not be null`

### ISSUE THREAD

**Issue by dtokar-pcty** [pendo-io/pendo-mobile-sdk#201]
**Platform + Version**
Android 10, 12, 14

**SDK Version**
3.4.2.6827

**Framework**
Native Android with Compose.

**Describe the bug**
Crash in the app during startup. 

**To Reproduce**
Not reproducible. Attached log is from Crashlytics. It is not crashing all the time. Just 5 crashes in last few days during testing our builds. But this code is not in production yet so the user base is very small at the moment.

**Expected behavior**
App is not crashing.

**Logs**
```
Caused by java.lang.NullPointerException: getScreenManager(...) must not be null
       at sdk.pendo.io.actions.ActivationManager.getScreenManager(:6)
       at sdk.pendo.io.actions.ActivationManager.<clinit>(:34)
       at sdk.pendo.io.PendoInternal.a(SourceFile:21)
       at sdk.pendo.io.Pendo.startSession()
       at com.myapplication.analyticsimpl.AnalyticsRepositoryImpl$startSession$2.invokeSuspend(AnalyticsRepositoryImpl.kt:67)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```        

**Sample Code**
```
 private suspend fun startSession(
        visitorId: String? = null,
        companyCode: String? = null,
        accountData: Map<String, Any>? = null,
        environment: String,
    ) {
        withContext(dispatchers.Default) {
            Pendo.startSession(visitorId, companyCode, mapOf("environment" to environment), accountData)
        }
    }

override suspend fun initAnalytics(context: Context) = withContext(dispatchers.Default) {
        Pendo.setup(context, BuildConfig.PENDO_API_KEY.decode(), null, null)    
    }
```

**Additional context**
We are not creating and setting options with setJetpackComposeBeta(true) now. Might this be the cause of the crash? 

`val options = PendoOptions.Builder().setJetpackComposeBeta(true).build()`

**Comment by noambartouv** [comment]
Hi Daniel,

Please see [integration instructions](https://github.com/pendo-io/pendo-mobile-sdk/blob/master/android/pnddocs/native-android.md#step-2-pendo-sdk-integration). The setup method needs to be called first thing when your application launches on the **main thread** from the Activity onCreate method. Similarly try calling the startSession from the main thread from the Activity/fragment where you start tracking your visitors. Internally our methods move network requests to background threads not to block the main thread. You are not required to call setJetpackComposeBeta(true), I don't see this as related to what you are experiencing.

I believe the crash is occurring as the Setup method must complete before the StartSession method can be called (the Setup method initializes the ScreenManager which is causing the null pointer exception). Probably the two coroutines are racing each other, not allowing the Setup method to initialize the ScreenManager properly before the StartSession method starts running its logic. Calling both from the main thread should force them to run sequentially eliminating the possibility for a crash.

**Comment by JKuliska-pcty** [comment]
Hello,
I took over the task of fixing this from Daniel on our side.

So I thought I'd use the the `setup`'s function parameter `pendoPhasesCallback` to recognize the initialisation has successfully finished when the `onInitComplete()` callback gets called, so that I can call the `startSession` function, but the `onInitComplete` never gets called for me. Is that function not meant for this purpose or am I doing something wrong?

**Comment by rotemelem6** [comment]
Hi @JKuliska-pcty,
If you call Setup and StartSession one after the other from the same corutine it's enough to guarentee StartSession is run after Setup has finished.
However, the OnInitComplete should be called if you set it up.
Did the onInitFailed was also not called?
You can set Pendo.setDebugMode(true), run your code and add the logs here so we can look at the logs and find what went wrong

**Comment by noambartouv** [comment]
Resolving the issue. Let us know if you encounter any further issues.
