### ISSUE TITLE
Unable to connect the configured iOS App with Pendo Debugger

### ISSUE THREAD

**Issue by apoorv-trikha-ev** [pendo-io/pendo-mobile-sdk#216]
**Platform + Version**
iOS 17.7

**SDK Version**
3.2.0.8353

**Framework**
Native

**Describe the bug**
We are trying to connect our iOS App with Pendo Debugger to tag new screens but when we scan the QR code it launches the app but Pendo Overlay buttons are not visible.
We have configured info.plist with URL types(pendo pairing) and have SceneDelegate configured with:
```
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        if let url = URLContexts.first?.url, url.scheme?.range(of: "pendo") != nil {
            pendoHelper.initWith(url: url)
        }
    }
```

**To Reproduce**
It was working before, but now it stopped working.

**Expected behavior**

**Logs**
If applicable, please add crash logs OR pendo logs (can be turned on with `PendoManager.shared().setDebugMode(true)`)

**Sample Code**

**Additional context**

**Comment by udilevin** [comment]
Can you try leave the app open at a point that setup and startSession are already called and then read the QR code?

**Comment by rasika-v-23** [comment]
Hi @apoorv-trikha-ev, did you get any solution for above problem?
