### ISSUE TITLE
Pendo is crashing opening a bottom menu in ReactNative

### ISSUE THREAD

**Issue by EduardoSellanes** [pendo-io/pendo-mobile-sdk#35]
Hi Team,
we have integrated Pendo in a ReactNative application, 
everything works perfectly, except at a specific UI in which we show a bottom menu, where Pendo crashes..

We also tried removing all render components from the menu (leave it blank with no options) and it still crashing.

we are using this module at that menu
https://github.com/gorhom/react-native-bottom-sheet

Attached crash screen,

any idea? Anything we can do?
 
thanks,
Eduardo.

![crash_02](https://user-images.githubusercontent.com/5940718/234653139-9d02ca96-771a-4e3b-a2b2-f86fdd1270c4.jpg)

**Comment by MikePendo** [comment]
@EduardoSellanes 
Can  you please provide minimal sample project for us to reproduce. It will be much faster for us to spot the issue

**Comment by MikePendo** [comment]
@EduardoSellanes
Any progress on small sample?

**Comment by EduardoSellanes** [comment]
Will try to work on the sample this week.. thanks for your reply.

**Comment by MikePendo** [comment]
@EduardoSellanes 
Small update one of my colleagues is aware of that issue and working on it, should be fixed next week I will update in the thread.

**Comment by udilevin** [comment]
rn-pendo-sdk 2.21.2 was released today. Please update your plugin.

**Comment by EduardoSellanes** [comment]
that's nice... will take a look.. thanks!
