### ISSUE TITLE
Change SwiftUI modifier name from `.enableSwiftUI()`

### ISSUE THREAD

**Issue by macblazer** [pendo-io/pendo-mobile-sdk#37]
In general, I like the ease of having a view modifier that enables Pendo to start tracking things in SwiftUI views.  However, scattering a bunch of calls to `.enableSwiftUI()` throughout my code does not make a lot of sense to me.  I am already coding in SwiftUI so why would I want to enable it?  What am I enabling?  When I come back to this after six months of working on other things, and I'll definitely ask myself "why am I enabling SwiftUI from SwiftUI code?...oh, yeah, that's a Pendo thing."

It would be make a lot more sense in the code (especially to other developers who have not read the Pendo documentation) to see a modifier that is named `.enablePendo()`, or if you don't want to put the company name in there make it `.enableAnalytics()`.  I would be happy to scatter that through my SwiftUI views because then I know I'm making that view work with Pendo analytics.

**Comment by MikePendo** [comment]
Agree that's make sense initially it was `.enablePendo()` . I need to see if I can push it further

**Comment by MikePendo** [comment]
@macblazer I am sorry its hard for me to push it forward currently. 
If more clients will complain about it, I will try to raise that concern again.
I am closing the issue with your permission
