### ISSUE TITLE
Manage In-App pages for iOS is showing blank screen on Pendo panel

### ISSUE THREAD

**Issue by Muzzamil75** [pendo-io/pendo-mobile-sdk#39]
I am receiving a black blank screen when capturing the screen from iOS for mange in-app pages but Android works well for me.
I am using 
**rn-pendo-sdk": "2.21.1"**

<img width="292" alt="image" src="https://github.com/pendo-io/pendo-mobile-ios/assets/42649485/fb299cad-0a68-4319-bd7b-d2a5847cdcef">

@MikePendo

**Comment by MikePendo** [comment]
What kind of app is it?native, react native , react native navigation ?

**Comment by Muzzamil75** [comment]
its React Native

**Comment by MikePendo** [comment]
I guess it's react native navigation. if so could you please debug in via Xcode turn on view hierarchy debugger and look for the following window `RNNOverlayWindow`. it seems like we are picking that window to scan instead of your actual app window. If I am right this issue is already resolved and will be available in 2.22

**Comment by Muzzamil75** [comment]
So when you are releasing 2.22 ?

**Comment by Muzzamil75** [comment]
@MikePendo I think this issue relates to RNN , when you are releasing the new version with that fix ?
Also, you can fresh install the RN CLI with RNN u can get that issue !
@MikePendo

**Comment by MikePendo** [comment]
@Muzzamil75 
We will release the fix next week, BUT I am still not sure if that's is your issue. 
what framework u use for navigation RNN or react navigation?

**Comment by Muzzamil75** [comment]
@MikePendo 
I am using
 **"react-native-navigation": "7.27.1",**

**Comment by MikePendo** [comment]
@Muzzamil75 
We r trying to convince our management to release a HF for that issue BUT unfortunately I don't have the power over those decisions. So it either a HF in 2.21 or 2.22 (somewhere in June)

**Comment by Muzzamil75** [comment]
Yes waiting for the Fix as my prod release is also upcoming please consider this ticket on urgent!
