### ISSUE TITLE
WithPendoReactNavigation Typescript Issues

### ISSUE THREAD

**Issue by bhandanyan-nomad** [pendo-io/pendo-mobile-sdk#46]
Example app code:
```javascript
const PendoNavigationContainer = WithPendoReactNavigation(NavigationContainer);
...
return (
    <PendoNavigationContainer
      ...
      linking={linkingConfig}
      ref={navigationRef}
      ... >
      ...
    </PendoNavigationContainer>
);
```

I am getting typescript errors on both the "linking" and "ref" props:
linking: `Type 'LinkingOptions<RootStackParamList> | undefined' is not assignable to type 'LinkingOptions<{}> | undefined'.`
ref: `Type 'NavigationContainerRefWithCurrent<RootParamList>' is not assignable to type 'Ref<NavigationContainerRef<{}>> | undefined'.`

Both seem to be related to my app's param list object, which I defined following react navigation's recommendation [here](https://reactnavigation.org/docs/typescript/#specifying-default-types-for-usenavigation-link-ref-etc). I have yet to find a way to tell Pendo to use my param list, is it possible to do so with the current package?

Package versions:
```
"rn-pendo-sdk": "2.21.2",
"@react-navigation/native": "6.0.8",
```

**Comment by bhandanyan-nomad** [comment]
My workaround for now is:
```javascript
const PendoNavigationContainer = WithPendoReactNavigation(
  NavigationContainer,
) as typeof NavigationContainer;
```

**Comment by MikePendo** [comment]
@bhandanyan-nomad 
Strange, I don't see such error for instance  my sample code:
```
const navigationRef = useNavigationContainerRef();
	return (
		<BottomSheetContext.Provider
			<SafeAreaProvider>
				<PendoNavigationContainer
				ref={navigationRef}
				>
					<GestureHandlerRootView style={styles.container}>
						{getStackNavigator()}
						<PrimaryBottomSheet />
					</GestureHandlerRootView>
				</PendoNavigationContainer>
			</SafeAreaProvider>
		</BottomSheetContext.Provider>
	);
```
What do u initialize your  `navigationRef`?

**Comment by MikePendo** [comment]
@bhandanyan-nomad any progress on it? Will it be ok if we close your ticket?

**Comment by MikePendo** [comment]
@bhandanyan-nomad  I am closing the issue, feel free to ping us.

**Comment by bhandanyan-nomad** [comment]
```javascript
const navigationRef = useNavigationContainerRef();
```
nothing special there.

Have you specified global navigation param types as described [here](https://reactnavigation.org/docs/typescript/#specifying-default-types-for-usenavigation-link-ref-etc)? This seems to be what is causing my issue, because as soon as I comment out the entire `declare global` block those errors disappear.
