### ISSUE TITLE
Issue with the SDK page analytics not being counted accurately

### ISSUE THREAD

**Issue by spiffysown** [pendo-io/pendo-mobile-sdk#51]
**Platform + Version**
Windows, Google Chrome, Desktop version of Pendo.

**SDK Version**

**Framework**
e.g React Native

**Describe the bug**
The analytics on pages are not tracking clicks properly. Instead of serving as dynamic links, they're only tracking clicks on that specifically tagged item. For example, one page has 1000+ of the same icon - but only the first one tagged is being tracked. Would like all to be tracked without having to tag 1,000+ items.

**To Reproduce**
1. Go to 'https://app.pendo.io/s/4840580476633088/pages'
2. Click on 'https://app.pendo.io/s/4840580476633088/pages/1TOa9ZVTakU5_o0GY5eQOCImyqA'

**Expected behavior**
Expect this page to have 10x the amount of clicks as we have thousands of these brand overview pages. Is there any way to track every brand overview page click instead of having to tag them all 1x1?

**Logs**

**Sample Code**

**Additional context**
Was told to log this by Ash & Brent on the Pendo team. Hoping I did it right. Thanks

**Comment by MikePendo** [comment]
@spiffysown 
Just want to make sure I got the issue right. You have an ui element that repeats it self and u want to have all the analytics be linked to this single element?
1. Maybe you could share a print screen of the screen and mark which ui element u r talking about? 
(in general u should be able to set feature rules for that element that will mark additional same elements as the same)

**Comment by MikePendo** [comment]
@spiffysown 
I also noticed that your bottom navigation bar is not taggbel (well that is a BUG ) do you think u can open an additional issue for that? (I think you are not the only one who might have it)

**Comment by spiffysown** [comment]
@MikePendo here is a [screen recording](https://photos.app.goo.gl/JoUiZ7gyU8ya83ei6) of the issue with a bit of context into what I mean.

I don't see a rule in Pendo that would allow me to mark additional elements the same. And a man named Brent from Pendo joined our Dashboard to explore and told me to log in here as he could not figure it out either.

**Comment by MikePendo** [comment]
When she press on the company icon/cell it moves her to your **Brand Overview Page** page. each view of that page will be calculate as page view (Under the hood we count number of views of the following page **CompanyOverview**  so it doesn't matter what company u press u will get the analytics for that page)

On the **Explore Page** I see that u can tag the Follow/Unfollow buttons inside the cell, but I guess the whole cell should be clickable, correct me if I am wrong.
Maybe u can  share a snippet of how you have implemented this row of cells so we will check why the whole cell is not clickable. 
In general maybe some very minimal sample mock project that include this row of cell and bottom bar can be provided by you so we will look more carefully and fix it our side if needed

**Comment by MikePendo** [comment]
@spiffysown 
also please update to the latest version currently u r on 2.20.1 our last on 2.21.3

**Comment by MikePendo** [comment]
@spiffysown 
please see if our answer make sense for u

**Comment by MikePendo** [comment]
@spiffysown I am closing the issue, please feel free to ping us.
