### ISSUE TITLE
Navigation bar at bottom of mobile app is untaggable in Pendo Pages

### ISSUE THREAD

**Issue by spiffysown** [pendo-io/pendo-mobile-sdk#52]
**Platform + Version**
e.g IOS, Android - mobile app

**SDK Version**

**Framework**
e.g React Native

**Describe the bug**
When I am trying to tag elements within pages of our app, the navigation buttons are not taggable/trackable. As [seen here.](https://photos.app.goo.gl/5mD7mVq7aMrmuQeY7)

**To Reproduce**
1. Go to 'https://app.pendo.io/s/4840580476633088/pages/-Y6cs_M-cUz_tla7Jb7-Em8V6E8?pendo-designer=eyJpZEZvckFwcCI6NDkyMzAyNDYyMjAyNjc1MiwidHlwZSI6Im1vYmlsZVBhZ2VNYW5hZ2UiLCJpZEZvclR5cGUiOiItWTZjc19NLWNVel90bGE3SmI3LUVtOFY2RTgiLCJkaXNhYmxlRmV0Y2hBZ2VudEFQSUtleSI6dHJ1ZSwia2VlcFVybFRva2VuIjp0cnVlLCJob3N0IjoiaHR0cHM6Ly9hcHAucGVuZG8uaW8iLCJ0YXJnZXQiOiJtb2JpbGUiLCJkZXNpZ25lcklkIjoiZGE2OWMwNzUtZWI3My00YzU5LTk3NmYtNzlhNDE2OTU1MDM4In0%3D'
2. Notice the bottom navigation menu is not taggable. 

**Expected behavior**
I would expect to be able to tag when users are maneuvering our menu. This is also becoming challenging because we cannot create guides that are impacted from menu buttons. 

**Logs**
If applicable, please add crash logs OR pendo logs (can be turned on with `PendoManager.shared().setDebugMode(true)`)

**Sample Code**

**Additional context**

**Comment by MikePendo** [comment]
@spiffysown 
any chance you can share small snippets of how you implement bottom navigation bar (maybe u have a small sample app that we could use to reproduce).( @udilevin we need to put end to this issue, lets look at it together)

**Comment by spiffysown** [comment]
Our main developer is on vacation today, but I will follow up on this on Monday when he returns. We do have a testflight for pre-launch, I know that. Thanks for your help I'll follow up early next week.

**Comment by MikePendo** [comment]
@spiffysown 
any progress on that?

**Comment by MikePendo** [comment]
@MadisonWeber 
We tried to reproduce the issue with your sample code but everything was taggable on our side. Maybe you can create a minimal  sample app to share with us?

**Comment by MikePendo** [comment]
@MadisonWeber @spiffysown 
I am closing the issue with your permission for now. We didnt manage to reproduce the issue. 
If you can provide us with sample minimal reproducible project we will be happy to look in to it.
