### ISSUE TITLE
iOS, PendoManager.shared().pauseGuides(true) doesn't work

### ISSUE THREAD

**Issue by vadimux** [pendo-io/pendo-mobile-sdk#72]
**Platform + Version**
IOS 16.6

**SDK Version**
SDK version identified:	'2.22.1.7434'

**Framework**
Native

**Describe the bug**
We use internal flag for showing/hiding Pendo Guides, but it looks SDK doesn't stop showing any guides if our flag is `false`

We call `PendoManager.shared().pauseGuides(true)` or `PendoManager.shared().dismissVisibleGuides()`, but guide is appeared anyway. It works as expected for Android SDK.

**To Reproduce**
1. Init Pendo SDK
2. call `PendoManager.shared().pauseGuides(true)`
3. See Pendo guide

**Expected behavior**
no any Pendo guides after calling `PendoManager.shared().pauseGuides(true)`

**Logs**
```
[Pendo] [Friday, 1 September 2023 at 11:45] ✅ canDisplay set to 1
[Pendo] [Friday, 1 September 2023 at 11:45] ✅ UserDefaults successfully written to file
[Pendo] [Friday, 1 September 2023 at 11:45] ✅ UserDefaults Synchronization Finished
[Pendo] [Friday, 1 September 2023 at 11:45] ✅ Assets were loaded successfully
[Pendo] [Friday, 1 September 2023 at 11:45] ✅ Window (address: 0x1053c8f10) of type PopupWindow has set window level to: 2004.000000
[Pendo] [Friday, 1 September 2023 at 11:45] ✅ Guide successfully displayed, guideId: S___8
```

**Sample Code**
```
 @objc func initSDK() {
      PendoManager.shared().setup(KEY)
      isPendoGuidesEnabled ? PendoManager.shared().resumeGuides() : PendoManager.shared().pauseGuides(true)
}

```

**Additional context**
looks like `PendoManager.shared().pauseGuides(true)` doesn't affect hiding of the guide and guide is appeared anyway

**Comment by MikePendo** [comment]
@vadimux 
The issue here is that u call them right after setup.
Setup call doesnt fetch any guides , the api that fetches the guides is startSession. If there is no session pause guides has no effect. 
Basically if u want to pause guides u will need to call it after StartSession

**Comment by vadimux** [comment]
@MikePendo thank you for clarification, I did it after StartSession, but I still have the guide as appeared

```
    @objc func visitor(userId: String, accountId: String) {
        let visitorData = prepareVisitorData()
        PendoManager.shared().startSession(userId,
                                           accountId: accountId,
                                           visitorData: visitorData,
                                           accountData: nil)

        PendoManager.shared().pauseGuides(true)
    }
```

**Comment by vadimux** [comment]
@MikePendo cool, thanks for workaround.

About your question - `PendoManager.shared().pauseGuides(true)` doesn't stop/pause any guides even when we use a guide in the middle of our application (like at the end of some flow), not an app launch only. When I use Test Full Flow on Device feature (connect device with QR code) and check some Track Event, I still see guide, but I expect don't see it, because `PendoManager.shared().pauseGuides(true)` has been called for this session.

**Comment by MikePendo** [comment]
@vadimux 
yes, you are correct the bug not only related to app launch guides. it relates to all guides if `pauseGuide` get called before `startSession` has finished its full guide initialization (I  edited my previous comment)
Regarding `pauseGuide` api when you are in the Test Full Flow (pairing mode). I see no reason why to call this api as the test full flow should simulate the appearance of the guide. In any case I will add it to our bug description so we will check that case also
