### ISSUE TITLE
Dexguard builds throwing error on version 2.17.x and above

### ISSUE THREAD

**Issue by rishabh876** [pendo-io/pendo-mobile-sdk#73]
**Platform + Version**
Android

**SDK Version**
[2.22.+, 2.17.+]
**Framework**
Native

**Describe the bug**
While generating release apk with dexguard enabled. Getting following error
com.guardsquare.dexguard.bSU: Can't find common super class of [external.sdk.pendo.io.mozilla.javascript.tools.debugger.FilePopupMenu] (with 1 known super classes: external.sdk.pendo.io.mozilla.javascript.tools.debugger.FilePopupMenu and 1 unknown classes: javax.swing.JPopupMenu) and [java.lang.Exception] (with 3 known super classes: java.lang.Object, java.lang.Throwable, java.lang.Exception)

**To Reproduce**
1. Add dexguard to the project
2. Generate release apk

**Expected behavior**
There shouldn't be an error

**Logs**

> com.guardsquare.dexguard.aOv: Unexpected error occurred during processing.
> 	at com.guardsquare.dexguard.cuT.b(DexGuard9.4.17:50)
> 	at com.guardsquare.dexguard.aOs.main(DexGuard9.4.17:15497)
> Caused by: com.guardsquare.dexguard.bSU: Can't find common super class of [external.sdk.pendo.io.mozilla.javascript.tools.debugger.FilePopupMenu] (with 1 known super classes: external.sdk.pendo.io.mozilla.javascript.tools.debugger.FilePopupMenu and 1 unknown classes: javax.swing.JPopupMenu) and [java.lang.Exception] (with 3 known super classes: java.lang.Object, java.lang.Throwable, java.lang.Exception)
> 	at com.guardsquare.dexguard.bUh.a(DexGuard9.4.17:551)
> 	at com.guardsquare.dexguard.bUh.c(DexGuard9.4.17:319)
> 	at com.guardsquare.dexguard.bUh.d(DexGuard9.4.17:224)
> 	at com.guardsquare.dexguard.bUl.d(DexGuard9.4.17:273)
> 	at com.guardsquare.dexguard.bUl.d(DexGuard9.4.17:160)
> 	at com.guardsquare.dexguard.bUg.d(DexGuard9.4.17:399)
> 	at com.guardsquare.dexguard.bSQ.a(DexGuard9.4.17:145)
> 	at com.guardsquare.dexguard.bSR.e(DexGuard9.4.17:115)
> 	at com.guardsquare.dexguard.bSE.a(DexGuard9.4.17:905)
> 	at com.guardsquare.dexguard.bSE.e(DexGuard9.4.17:793)
> 	at com.guardsquare.dexguard.bSE.a(DexGuard9.4.17:1325)
> 	at com.guardsquare.dexguard.bER.a(DexGuard9.4.17:64)
> 	at com.guardsquare.dexguard.bun.c(DexGuard9.4.17:223)
> 	at com.guardsquare.dexguard.bSE.c(DexGuard9.4.17:1271)
> 	at com.guardsquare.dexguard.bSE.d(DexGuard9.4.17:773)
> 	at com.guardsquare.dexguard.bSE.e(DexGuard9.4.17:444)
> 	at com.guardsquare.dexguard.bSE.b(DexGuard9.4.17:401)
> 	at com.guardsquare.dexguard.csj.b(DexGuard9.4.17:105)
> 	at com.guardsquare.dexguard.bun.b(DexGuard9.4.17:138)
> 	at com.guardsquare.dexguard.bue.d(DexGuard9.4.17:148)
> 	at com.guardsquare.dexguard.bwo.c(DexGuard9.4.17:94)
> 	at com.guardsquare.dexguard.bFt.c(DexGuard9.4.17:57)
> 	at com.guardsquare.dexguard.bue.c(DexGuard9.4.17:140)
> 	at com.guardsquare.dexguard.btZ.e(DexGuard9.4.17:695)
> 	at com.guardsquare.dexguard.bDY.visitAnyClass(DexGuard9.4.17:46)
> 	at com.guardsquare.dexguard.bEy.b(DexGuard9.4.17:40)
> 	at com.guardsquare.dexguard.btZ.a(DexGuard9.4.17:544)
> 	at com.guardsquare.dexguard.bFM.c(DexGuard9.4.17:189)

**Sample Code**
na

**Additional context**
na

**Comment by DavidFaermanPendo** [comment]
Thanks for reaching out to Pendo.
In our consumer [pro guard file](https://github.com/pendo-io/pendo-mobile-sdk/blob/master/android/pnddocs/pendo-proguard.cfg), we specifically add "-dontwarn javax.swing.**" It seems Dexguard is ignoring it.  
Rest assured you can safely ignore this warning. 

Thanks
