### ISSUE TITLE
Pendo native plugin is not available on test

### ISSUE THREAD

**Issue by trajano** [pendo-io/pendo-mobile-sdk#81]
**Platform + Version**
e.g IOS 16, Android

**SDK Version**
"rn-pendo-sdk": "^2.22.3",

**Framework**
 Expo using React Navigation, 

**Describe the bug**
This message appears on Jest logs whenever the rn-pendo-sdk is loaded
>     console.info
>      [rn-pendo-sdk]  Pendo native plugin is not available. Ignoring Call. Please note that if you are using Expo, Expo Go is not supported by Pendo because Pendo SDK has a native plugin that is not part of the Expo Go app.

I am thinking that this message should only be generated when `PendoSDK.setup` is actually called and not as a side effect of module load.

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, please add crash logs OR pendo logs (can be turned on with `PendoManager.shared().setDebugMode(true)`)

**Sample Code**
Code snippet or Sample project

**Additional context**

**Comment by MikePendo** [comment]
It means that the plugin can find the native library. Can you make sure that the native lib is there? (We dont support the Expo GO app)

**Comment by MikePendo** [comment]
@trajano 
Please let us know if our previous comment resolve the issue

**Comment by trajano** [comment]
No @MikePendo Ideally it shouldn't find the native module because it is running in a Jest test.  Sentry at least doesn't put noise on the logs even though it knows it is not working.

**Comment by MikePendo** [comment]
@trajano 
My apologizes we usually see this error in situations when people use GO app. So I have mistakenly associated your issue with that one

**Comment by MikePendo** [comment]
@trajano 
So unfortunately its under the `info` log and I dont see any suggestion that can allow us to silent it currently.
Would it be possible for you to mock it?

**Comment by MikePendo** [comment]
@trajano 
We have opened and internal ticket on our side to provide an option to set `loging level` api.  (Unfortunately I cant promise any deadlines when it will be resolved)

**Comment by DavidFaermanPendo** [comment]
closed by mistake

**Comment by udilevin** [comment]
@trajano our next release (3.3) will decrease the logging significantly (only calls to Pendo API will add a log)
