### ISSUE TITLE
Nuget package for MAUI is missing net8.0 target

### ISSUE THREAD

**Issue by velocitysystems** [pendo-io/pendo-mobile-sdk#82]
**Platform + Version**
.NET 8.0

**SDK Version**
2.22.6.6006

**Framework**
MAUI

**Describe the bug**
NuGet package for the MAUI SDK is missing a `net8.0` target.
This prevents a MAUI project (with Pendo) from being referenced by a unit test project i.e. xUnit runner.

**To Reproduce**
1. Create an empty MAUI project
2. Add `pendo-maui` NuGet package to project
3. Create an empty xUnit test project with a `net8.0` target
4. Add MAUI project as a project reference to test project

**Expected behavior**
NuGet package should include a `net8.0` target, in addition to iOS, Android, Mac Catalyst targets.
See an example [here](https://www.nuget.org/packages/Microsoft.Maui.Controls.Maps/) for the `Microsoft.Maui.Controls.Maps` project.

**Comment by TehilaTaub** [comment]
Thanks for reaching out.
Currently, we do not support .net 8.0 yet, but it is in our roadmap. We will keep you updated with the timeline once we will have it.

**Comment by velocitysystems** [comment]
Thanks @TehilaTaub. As an interim workaround, can you please add a `net6.0` target to the package?
This will resolve the issue in the meantime for users on .NET 6.0 and .NET 7.0.

**Comment by TehilaTaub** [comment]
The current package is compatible with .NET 6.0, and the 3.0 package will be available in a week and compatible with .NET 7.0.

**Comment by velocitysystems** [comment]
> The current package is compatible with .NET 6.0, and the 3.0 package will be available in a week and compatible with .NET 7.0.

The current package is targeted for `net6.0-android31.0`, `net6.0-ios15.0` and `net6.0-maccatalyst16.1` but it is _missing_ a target for `net6.0`. A `net6.0` target is required in order to add the MAUI project containing Pendo to a test runner project i.e. with xUnit or NUnit.

For the new package compatible with net7.0, this would mean adding a vanilla `net7.0` target to the package.

**Comment by velocitysystems** [comment]
@TehilaTaub Thanks for adding a vanilla `net7.0` target to the latest pendo-maui package!
Everything now compiles and works perfectly with an xUnit test runner.
