### ISSUE TITLE
clang++ exited with code 1 when compiling for ios-simulator on arm64

### ISSUE THREAD

**Issue by albyrock87** [pendo-io/pendo-mobile-sdk#87]
**Platform + Version**
iOS ARM64 Simulator (Mac M1...M3)

**SDK Version**
3.0.0.7965

**Framework**
MAUI .NET 8

**Describe the bug**
This is the same issue AppCenter library has: https://github.com/microsoft/appcenter-sdk-dotnet/issues/1755

When targeting iOS Simulator on MacBook M1 (arm64) there's no way to compile the project with Pendo included as package reference.

**To Reproduce**
Using a MacBook M1..3
Create a MAUI project
Embed Pendo as described in docs
Compile targeting iOS Simulator.

**Expected behavior**
Project builds.

**Logs**
```
 Build / Console Error 1: 
 bash
 3>Xamarin.Shared.Sdk.targets(1556,3): Error  : clang++ exited with code 1:
 ld: building for iOS Simulator, but linking in dylib built for iOS, file '......obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/Pendo.framework/Pendo'
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by velocitysystems** [comment]
@albyrock87 Ran into this same issue. Are you trying to compile with Rider?
As a workaround, I can build/deploy to the iOS simulator with VS for Mac with the .NET 8 preview feature turned on.

**Comment by albyrock87** [comment]
Alright, I will proceed that way for now, thanks.

**Comment by albyrock87** [comment]
@velocitysystems I'll reopen the issue because this is not a problem with Rider: I can reproduce it using a standalone terminal

```
dotnet build MyProject -f net8.0-ios -r iossimulator-arm64
```

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.0.8478/targets/Xamarin.Shared.Sdk.targets(1556,3): error : clang++ exited with code 1: [/Users/myusername/my-project/MyProject/MyProject.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.0.8478/targets/Xamarin.Shared.Sdk.targets(1556,3): error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/myusername/my-project/MyProject/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/Pendo.framework/Pendo' [/Users/myusername/my-project/MyProject/MyProject.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.0.8478/targets/Xamarin.Shared.Sdk.targets(1556,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/myusername/my-project/MyProject/MyProject.csproj::TargetFramework=net8.0-ios]
```

**Comment by MikePendo** [comment]
@albyrock87 
We dont support .net8 yet, can u try to build with .net7 and see if u have the same error?

**Comment by albyrock87** [comment]
@MikePendo same error, with different text

I've tried using the sample `Calculator` [project from here](https://github.com/dotnet/maui-samples/tree/20ae5ee72d1ecadcd3871cb16153242b6a1a96c3) and adding a `global.json`

```
{
  "sdk": {
    "version": "7.0.100",
    "rollForward": "latestFeature"
  }
}
```

```
dotnet --version
7.0.401
```

```
dotnet build Calculator -f net7.0-ios -r iossimulator-arm64
```

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : clang++ exited with code 1: [/Users/myuser/Downloads/maui-samples-20ae5ee72d1ecadcd3871cb16153242b6a1a96c3/7.0/Apps/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : ld: warning: ignoring duplicate libraries: '-lSystem.IO.Compression.Native', '-lSystem.Native', '-lSystem.Net.Security.Native', '-lSystem.Security.Cryptography.Native.Apple', '-lcompression', '-lmono-component-debugger', '-lmono-component-diagnostics_tracing', '-lmono-component-hot_reload', '-lmonosgen-2.0', '-lxamarin-dotnet-debug' [/Users/myuser/Downloads/maui-samples-20ae5ee72d1ecadcd3871cb16153242b6a1a96c3/7.0/Apps/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : ld: building for 'iOS-simulator', but linking in dylib (/Users/myuser/Downloads/maui-samples-20ae5ee72d1ecadcd3871cb16153242b6a1a96c3/7.0/Apps/Calculator/src/Calculator/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/Pendo.framework/Pendo) built for 'iOS' [/Users/myuser/Downloads/maui-samples-20ae5ee72d1ecadcd3871cb16153242b6a1a96c3/7.0/Apps/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/myuser/Downloads/maui-samples-20ae5ee72d1ecadcd3871cb16153242b6a1a96c3/7.0/Apps/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
```

**Comment by MikePendo** [comment]
@albyrock87 
I have looked at the run time environments here:[rid-catalog]( https://learn.microsoft.com/en-us/dotnet/core/rid-catalog)
and I didnt find yours `iossimulator-arm64`. The one that I did find is `ios-arm64`. 
I have download the project and tried to build with that run time and it worked for me .
I changed the project a little [project snippets](https://gist.github.com/MikePendo/db5d74045feba0fd78cc9dd0ab15c2be)
To allow only iOS with .net7
and run the following: `dotnet build Calculator -r ios-arm64`
Can it try on your side?

**Comment by albyrock87** [comment]
@MikePendo I will try, but as far as I know, this is the PR introducing that RID, and it appears to me it targets .NET6 release especially considering it's from March 2021.
https://github.com/dotnet/runtime/pull/49305

Apparently the documentation you linked is not up to date.

**Comment by albyrock87** [comment]
Actually look in this section:
https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#known-rids

> The following list shows a small subset of the most common RIDs used for each OS.
> For the latest and complete version, see the PortableRuntimeIdentifierGraph.json in the dotnet/sdk repository.

https://github.com/dotnet/sdk/blob/main/src/Layout/redist/PortableRuntimeIdentifierGraph.json

**Comment by MikePendo** [comment]
@albyrock87 
Unfortunately my knowledge related to Xamarin/Maui is limited. I have opened an issue here: https://github.com/dotnet/maui/issues/19406
Lets see what they can say

**Comment by velocitysystems** [comment]
@albyrock87 Rider 2023.3.1 has been released and references a fix for a related issue.
https://youtrack.jetbrains.com/issue/RIDER-76794/Cannot-deploy-MAUI-project-to-physical-iOS-device-because-of-RuntimeIdentifier

**Comment by cleardemon** [comment]
Would be nice to have a fix for this, especially since more will be updating to .NET 8 over time!

It seems having Pendo compile their DLL to use a proper `.xcframework` package that outputs for each architecture and configuration appropriately is the way to go (as discussed in the issue raised in the MAUI repo). There are various links on the Internet about moving from `.framework` to `.xcframework`: [strava](https://medium.com/strava-engineering/convert-a-universal-fat-framework-to-an-xcframework-39e33b7bd861), [fusion](https://medium.com/fusionui/from-fat-frameworks-to-xcframeworks-or-how-to-support-arm64-for-ios-simulators-a53f9f097f83), [apple](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle).


Currently, the only workaround I can find for Pendo is to use Visual Studio for Mac (with .NET 8 support enabled in Preview Features), and forcing it to use `iossimulator-x64` in the app `csproj`. Or, simply, removing Pendo entirely from the build. Neither of these workarounds are ideal.

In response to other comments above, Rider now works fine with .NET 8 since their recent update. 

Also to reiterate, I am not observing this issue on actual iOS devices, it is purely an iOS Simulator issue. Developer quality of life is as important as end-users (we are end-users too! 😄)

**Comment by MikePendo** [comment]
@cleardemon We are working on it.
@udilevin any progress about it?

**Comment by udilevin** [comment]
XCFramework support  in MAUI will be part of our next release.

**Comment by albyrock87** [comment]
Thank you @udilevin , very much appreciated!

**Comment by shlomipendo** [comment]
FYI, The relevant version for this fix is 3.1.0

**Comment by albyrock87** [comment]
Thank you very much!

**Comment by shalinjirawla** [comment]
I still face the same issue in .Net 8 while running a MAUI project in VScode on MacBook Air M2

**Comment by udilevin** [comment]
Will review the issue and let you know .
