### ISSUE TITLE
While building for macOS, no library for this platform was found in

### ISSUE THREAD

**Issue by AyaBassi** [pendo-io/pendo-mobile-sdk#91]
**Platform + Version**
iOS 13
**SDK Version**
3.0.0

**Framework**
In a Swift package to be used for SwiftUI
 Native, SwiftUI

**Describe the bug**
After adding the Pendo  Url .git to Package.swift as dependency this error is shown when building. 

/Users/TestUser/Library/Developer/Xcode/DerivedData/TestPackage-ddolwbkmejmywdgfegtcxrsndohd/SourcePackages/artifacts/pendo-mobile-sdk/Pendo/Pendo.xcframework:1:1: While building for macOS, no library for this platform was found in '/Users/TestUser/Library/Developer/Xcode/DerivedData/TestPackage-ddolwbkmejmywdgfegtcxrsndohd/SourcePackages/artifacts/pendo-mobile-sdk/Pendo/Pendo.xcframework'.

**To Reproduce**
1. Go to Package.swift
2. Click on Add Pendo as third party Library
3. Scroll down to Build

**Comment by MikePendo** [comment]
Currently the SDK is  for IOS **only**.

**Comment by MikePendo** [comment]
@AyaBassi 
I am not sure why you are building for macOS, The SDK is just a binary that is already build, you will need to see in your project configuration. Maybe u have multiple targets? so you can delete the SDK in the MacOS target in Framewrok,Libararies and keep it in the iOS target only. 
Other wise create us a sample project an we will look
